import * as React from 'react';
import Head from "next/head";
import styled from "styled-components";
import Layout from "../components/Layout";
import { FormattedMessage } from "react-intl";

const Hero = styled.div`
  position: relative;
  padding: 24.2vh 30vw 4.5vh 8vw;
  overflow: hidden;

  @media (min-width: 768px) {
    padding: 6.5vh 48vw 6.5vh 18vw;
    flex: 1;
  }
`;

const HeroTitle = styled.h1`
  position: relative;
  font-size: 47px;
  line-height: 1.1em;
  font-weight: 700;
  margin-block-end: 0.6em;
  z-index: 1;

  @media (min-width: 768px) {
    font-size: 72px;
    margin-block-end: 0.5em;
  }
`;

const HeroSubtitle = styled.p`
  position: relative;
  font-size: 11.8px;
  line-height: 1.5em;
  font-weight: 500;
  z-index: 1;

  @media (min-width: 768px) {
    font-size: 18px;
  }
`;

const HeroImage = styled.img`
  position: absolute;
  bottom: 0;
  right: -53%;
  width: 659px;

  max-width: 1100px;
  pointer-events: none;

  @media (min-width: 768px) {
    left: unset;
    bottom: -22vh;
    right: 0;
    width: 69%;
  }
`;

const Home: React.FC<{}> = () => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
        <HeroTitle>
          <FormattedMessage id="index.hero.title" />
        </HeroTitle>
        <HeroSubtitle>
          <FormattedMessage id="index.hero.subtitle" />
        </HeroSubtitle>
        <HeroImage src="/images/hero.png" />
      </Hero>
    </Layout>
  );
}

export default Home;